name: Simple test so I can sleep better

on:
  push:
  workflow_dispatch:

jobs:
  check_them_endpoints:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install env
      run: |
        sudo apt install nodejs npm && npm i -g html-validate
        pip install -r requirements.txt
    - name: Test the endpoints
      run: |
        ./cmd.sh run &
        sleep 2
        curl -v "http://localhost:32168/comments?for=example" > out.html
        cat out.html
        html-validate out.html
        curl -v "http://localhost:32168/comments?for=example/deeper" > out.html
        cat out.html
        html-validate out.html
        curl -v "http://localhost:32168/comments?for=/example/deeper" > out.html
        cat out.html
        html-validate out.html

